apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-job
annotations:
  argocd.argoproj.io/hook: PpstSync 
  argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep",  "10"]
      restartPolicy: Never
      
