apiVersion: batch/v1
kind: Job
metadata:
  name: post-sync-job
  namespace: argocd  # Ensure this is the correct namespace
  annotations:
    argocd.argoproj.io/hook: PostSync 
    # argocd.argoproj.io/hook-delete-policy: HookFailed
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
      - name: sleep
        image: alpine:latest
        command: ["sleep", "10"]
      restartPolicy: Never

      
